Vagrant.configure(2) do |config|

  config.vm.define :jekyll do |jekyll|
    jekyll.vm.box = 'ubuntu/trusty64'
    jekyll.vm.hostname = 'jekyll'
    jekyll.vm.network :forwarded_port, guest: 4000, host: 4000
    jekyll.ssh.shell = 'bash'

    jekyll.vm.provision :shell, inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y tree git ruby-dev nodejs-legacy
      sudo gem install jekyll -v 2.5.3
    SHELL
  end

end
